---
title: "branch_workflow"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{branch_workflow}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
# library(staged.dependencies)
```

```
One implements a new feature called `feature1` that involves `repoB, repoC` with the dependency graph `repoA --> repoB --> repoC`, where `repoA` is an additional upstream dependency. One then notices that `feature1` requires a fix in `repoB`, so one creates a new branch `fix1/feature1/devel` on `repoB`. The setup can be summarized as follows:
```
repoB: fix1/feature1/devel, feature1/devel, devel
repoC: feature1/devel, devel
repoA: devel
```
A PR on repoB `fix1/feature1/devel --> feature1/devel` takes `repoB:fix1/feature1/devel, repoC: feature1/devel, repoA: devel`. This can be checked by setting `target = fix1/feature1/devel` and running `R CMD check` on `repoC`, or `check_downstream` on `repoB` (adding `repoC` to its downstream dependencies).
The PR on `repoB` and  `repoC` `feature1/devel --> devel` takes `repoB:feature1/devel, repoC: feature1/devel, repoA: devel`, setting `target = feature1/devel`.
```
