---
name: Docs 📚

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - inst/templates/**
      - _pkgdown.yml
      - DESCRIPTION
      - '**.md'
      - man/**
      - LICENSE.*
      - NAMESPACE
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main

jobs:
  docs:
    name: Pkgdown Docs 📚
    uses: insightsengineering/r.pkg.template/.github/workflows/pkgdown.yaml@handle-renv-for-docs
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
